### ISSUE TITLE
Not crafting the bedrock block and all the other things from this mod on version 1.20.6 and I decided to update the mod to 1.21 and I did it

### ISSUE THREAD

**Issue by 7789784** [TheCJBrine/bedrock-crafter#1]
I can't craft anything from this mod, even JEI doesn't show the crafting mod what to do?

**Comment by TheCJBrine** [comment]
Hello, sorry for the late reply. Thank you for the report!

Minecraft 1.21 changed the names of some data folders slightly (for example, "recipes" was renamed to "recipe"), so the most recent version of the mod that existed wouldn't work correctly. However, I've just released an update for 1.21 and Fabric, and recipes should be working in it. You can find the update here:
https://modrinth.com/mod/bedrock-crafter/version/1.3.2-MC1.21-Fabric

If you have the same issue in 1.20.6, unfortunately I'm not sure what the problem could be, as recipes seem to be working as they should in that version. Make sure the version of the mod matches your Minecraft version and modloader, in that case. (Currently, for Minecraft 1.20.5 and 1.20.6, I only have a Fabric version of the mod available)

If you still have problems with the mod after making sure you're using the right version, please let me know.
